### ISSUE TITLE
Can falco-exporter use a config file?

### ISSUE THREAD

**Issue by johanneskastl** [falcosecurity/falco-exporter#101]
Hi,

I am packaging falco-exporter as RPM for openSUSE, as I would like to use it on my infrastructure. I guess it does not need much configuration, but:

Instead of hacking the many CLI flags into a systemd unit, can falco-exporter use a configuration file?

I found no hint, so my guess is "NO". 

Is this is true, then I would work with a file setting a "ARGS" variable, that is used inside the systemd unit. This variable could hold the user's desired flags.

Thanks for creating falco-exporter, nice addition to the falco ecosystem!

**Comment by leogr** [comment]
Hey @johanneskastl 

You're right; falco-exporter only supports CLI flags (and no configuration file). It's based on https://github.com/spf13/pflag

Also, we are working to integrate falco-exporter functionality directly into Falco. The ETA for having this as a stable feature in Falco is not before Falco 0.39 (due by Sept) and falco-expoter will be deprecated at some point. 

That said, I will continue to maintain this tool until a full replacement is delivered. 

> Thanks for creating falco-exporter, nice addition to the falco ecosystem!
You're welcome! Thank you for using it :)

**Comment by johanneskastl** [comment]
Thanks for the fast confirmation. Then I know what to do.

Good news on the integration, I'll maintain the package for openSUSE until it is being deprecated :-)

**Comment by leogr** [comment]
> Thanks for the fast confirmation. Then I know what to do.
You're welcome!

> Good news on the integration, I'll maintain the package for openSUSE until it is being deprecated :-)

Good to know!

Out of curiosity, do you maintain the `falcoctl` package too?

Asso, I noticed there is no Falco package for openSUSE. By any chance, are you (or do you know someone who is) willing to maintain it? :thinking: 


cc @FedeDP @alacuku

**Comment by johanneskastl** [comment]
Yes, I also maintian the falcoctl package.

I have set aside some time this weekend to get started on the falco package, that is the last on my list... :-)

**Comment by leogr** [comment]
> I have set aside some time this weekend to get started on the falco package, that is the last on my list... :-)

This is great! Thank you :star_struck: Please, let us know if you need any support :pray:
