### ISSUE TITLE
Releasing procedure

### ISSUE THREAD

**Issue by Voronenko** [falcosecurity/falco-exporter#14]
**What would you like to be added**:
Do you plan to introduce releases, which would include pre-built binaries for a most popular platforms, like amd64? Smth similar to what nginx does for their exporter.
https://github.com/nginxinc/nginx-prometheus-exporter/releases

**Why is this needed**:
Having releases officially published, allows to use them in automation scenarios without need to dive into go compiling on every run.

**Comment by leodido** [comment]
Definitely yes
