### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by rhefner1** [falcosecurity/falco-exporter#15]
**What happened**:
Error: `2020/01/29 15:32:54 unable to connect: error loading the X.509 key pair: open /etc/falco/certs/client.crt: no such file or directory`

**What you expected to happen**:
falco-exporter to run normally

**How to reproduce it (as minimally and precisely as possible)**:
- `docker build -t falco-exporter:Dec_16_2019 -f docker/local/Dockerfile .`
- `docker run falco-exporter:Dec_16_2019 ./falco-exporter`

I am trying to run this exporter as a sidecar inside of the main Falco pod. I'm confused what the client-ca and client-cert flags are for. When Falco (version 0.18.0) starts, it doesn't create any of these certs in `/etc/falco`.  What should these flags contain to run the exporter successfully?

**Comment by leogr** [comment]
Hi @rhefner1 

To make it work, you should enable the gRCP API in the falco configuration and generate the required certificates as described [here](https://falco.org/docs/grpc/).
Finally, client certs must be accessibile from within the falco-explorer's container into the default path `/etc/falco/certs` or you can set [these env vars](https://github.com/falcosecurity/falco-exporter/blob/master/docker/local/Dockerfile#L6) to specify a custom paths.
