### ISSUE TITLE
Host Helm chart on stable/

### ISSUE THREAD

**Issue by AlexDHoffer** [falcosecurity/falco-exporter#25]
**Motivation**

Would like to include the falco-exporter in our monitoring pipeline, but can't find it living in a repository upstream.

**Feature**

Host the Falco exporter Helm chart on the stable/ repository.

**Comment by leogr** [comment]
Maybe we want to publish all charts [here](https://github.com/falcosecurity/charts)

**Comment by gdurandvadas** [comment]
It would be nice if `falco-exporter` is part of the helm charts so that we don't need to download on our own.

**Comment by leogr** [comment]
**Quick update**

We are in an on-going effort to implement the [releasing automation mechanism](https://github.com/falcosecurity/charts/issues/22) for our new [charts hub](https://github.com/falcosecurity/charts).

The first step to automate this process is almost implemented by https://github.com/falcosecurity/charts/pull/31 
The next step is to add the ability to release charts which source lives outside the https://github.com/falcosecurity/charts git repository (eg. `falco-exporter`).

Once that gets done and tested, I will add the `falco-exporter` chart to our charts hub. 
Hope very soon :partying_face:

/assign

**Comment by piraces** [comment]
Any updates on this?

**Comment by leogr** [comment]
We're deciding how to move other charts to https://github.com/falcosecurity/charts
The discussion is here: https://github.com/falcosecurity/charts/issues/47

After some considerations, I think I will move the helm chart to our `charts` repo, so it will be host in [our Helm Chart Repository](https://github.com/falcosecurity/charts#adding-falcosecurity-repository).

Luckily, we can move it later this week (after releasing Falco 0.24.0 that's scheduled for the 16th).
