### ISSUE TITLE
deployment: the exporter communicate round-robin to falco pods 

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco-exporter#26]
**Describe the bug**

Each falco-exporter instance should only connect to the Falco instance running on the same host.

But, we have realized that it is not working as expected with the provided helm chart and k8s resource files.

**Some more context**

Currently, there two headless services:
the gRPC service (exposed by falco) :point_right: https://github.com/helm/charts/blob/master/stable/falco/templates/service.yaml#L30
the metrics service (exposed by falco-exporter) :point_right: https://github.com/falcosecurity/falco-exporter/blob/master/deploy/k8s/falco-exporter/templates/service.yaml#L15
Then the falco-exporter tries to connect to falco-grpc.default.svc.cluster.local :point_right: https://github.com/falcosecurity/falco-exporter/blob/master/deploy/k8s/falco-exporter/templates/daemonset.yaml#L33
But by doing so, falco-exporter is communicating roundrobin to the falco pods, that's wrong.

**How to reproduce it**

Deploy Falco and the exporter as explained in the [blog post](https://falco.org/blog/falco-kind-prometheus-grafana/), then check connections between falco-exporter pods and falco-grpc service.

**Expected behaviour**

Each falco-exporter instance should only connect to the Falco instance running on the same host.

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**
Thanks to *AJ Christensen* for [having reported this problem in the #falco slack channel](https://sysdig.slack.com/archives/C19S3J21F/p1588630983387400).

**Comment by fujin** [comment]
I built out a design that uses a single daemonset (with a `-exporter` sidecar). cert-manager CA Issuer handles keypairs for the server (falco) and client (exporter). A single ClusterIP service exposes the metrics port's endpoints from the sidecars, which Prometheus scrapes via the typical annotation. I can see about posting the manifests if it is helpful (we use Jsonnet but I can render them to YAML).

The resources are as described:
- service account
- cluster role/binding
- configmaps [falco.yaml, rules, etc.]
- service [pointing at the metrics port]
- daemonset with multi-container
- ca keypair (for CA Issuer)
- ca issuer
- certificates for server and client

**Comment by leogr** [comment]
Since we will not have this problem with [gRPC over unix socket support](https://github.com/falcosecurity/client-go/pull/43) and it will be released soon, I believe the right choice is just to use the unix socket and remove the gRPC service over TCP from the helm chart.

As soon as the unix socket support is released, I will fix here.
