### ISSUE TITLE
Improve reliability of gRPC connections / communications

### ISSUE THREAD

**Issue by fujin** [falcosecurity/falco-exporter#27]
**Motivation**

I've configured Falco Exporter as a sidecar, which exposes some certain issues, particularly the delay during Falco's BPF probe compilation and gRPC server binding. This causes the exporter to generally go into CrashLoopBackOff due to error.

**Feature**

Implement backoff retry functionality for gRPC client creation, connection and subscription.

```
2020/05/19 00:25:50 exporter error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:5060: connect: connection refused", retrying after backoff of 1 second(s)
2020/05/19 00:25:51 exporter error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:5060: connect: connection refused", retrying after backoff of 2 second(s)
2020/05/19 00:25:53 exporter error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:5060: connect: connection refused", retrying after backoff of 4 second(s)
2020/05/19 00:25:57 exporter error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:5060: connect: connection refused", retrying after backoff of 8 second(s)
```

```
NAME          READY   STATUS    RESTARTS   AGE
falco-6ccmq   2/2     Running   0          58s
falco-hd2sh   2/2     Running   0          49s
falco-s74c5   2/2     Running   0          35s
falco-vm62v   2/2     Running   0          73s
falco-zhtc2   2/2     Running   0          82s
```

**Alternatives**

If I had used the current standard approach of multiple daemonsets/services I could have an initContainer waiting for the service (representing the Falco daemonset) to become available, with a sidecar it is not possible - I'd essentially need an initContainer _only_ for falco-exporter.

**Comment by DannyPat44** [comment]
@fujin I am encountering this same issue in my deployment. I have both Falco and my exporter running as Dameonsets. But if I have a rolling deploy occur on Falco the exporter will enter a crashloop back off where it can't recover. Could you explain or point me to documentation for the alternative you suggest?

**Comment by DannyPat44** [comment]
Ah I see you have a PR open already I will just wait for that then!

**Comment by fujin** [comment]
@DannyPat44 I have been running my branch in a staging environment for a number of hours now, if you want to build a container from it to try, otherwise if you want to pursue the initContainer approach, there is [an example here](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use). 

That approach would have the pod's non-initContainer containers wait for the sequence of initContainers to complete to success. You can pretty much have them do anything, in your case I'd say check that the gRPC service resolves and potentially opening a connection to it.
