### ISSUE TITLE
Falco-exporter events only seen for falco-exporter pods

### ISSUE THREAD

**Issue by georgebrianb** [falcosecurity/falco-exporter#34]
Hey guys, after many fails and thanks to Leonardo Grasso, I managed to deploy falco and falco-exporter on my 3 node GKE cluster with COS 1.15.9 v24. 

I have used helm to deploy an instance of the latest falco version and the git checkout  d56be55bb8c1bb1f216ef6f2f4f3cedc48347d24 for falco-exporter, and click to deploy Wordpress.

**Describe the bug**

The only metrics I see in Grafana dashboard are the ones for the falco-exporter pods.

I have checked the logs and falco does see events on other pods:

```
georgebrianb@cloudshell:~/falco-exporter (disertatie-utm-sysdig)$ kubectl exec wordpress-1-wordpress-0 -- touch /test
Defaulting container name to wordpress.
Use 'kubectl describe pod/wordpress-1-wordpress-0 -n default' to see all of the containers in this pod.
georgebrianb@cloudshell:~/falco-exporter (disertatie-utm-sysdig)$ kubectl logs falco-w4tvr | grep touch
09:58:02.459389088: Error File below / or /root opened for writing (user=root command=touch /test parent=<NA> file=/test program=touch container_id=bd0f695bd7c8 image=gcr.io/cloud-marketplace/google/wordpress/mysql) k8s.ns=default k8s.pod=wordpress-1-mysql-0 container=bd0f695bd7c8 k8s.ns=default k8s.pod=wordpress-1-mysql-0 container=bd0f695bd7c8
10:00:20.893554945: Error File below / or /root opened for writing (user=root command=touch /test parent=<NA> file=/test program=touch container_id=bd0f695bd7c8 image=gcr.io/cloud-marketplace/google/wordpress/mysql) k8s.ns=default k8s.pod=wordpress-1-mysql-0 container=bd0f695bd7c8 k8s.ns=default k8s.pod=wordpress-1-mysql-0 container=bd0f695bd7c8
10:02:16.710233784: Error File below / or /root opened for writing (user=root command=touch /test1 parent=<NA> file=/test1 program=touch container_id=bd0f695bd7c8 image=gcr.io/cloud-marketplace/google/wordpress/mysql) k8s.ns=default k8s.pod=wordpress-1-mysql-0 container=bd0f695bd7c8 k8s.ns=default k8s.pod=wordpress-1-mysql-0 container=bd0f695bd7c8
```

**How to reproduce it**
Installed yugabyteDB using the following tutorial:
https://blog.yugabyte.com/getting-started-with-falco-runtime-security-and-cloud-native-distributed-sql-on-google-kubernetes-engine/

Generate TLS certs using falcoctl:
`FALCOCTL_NAME=falco-grpc.default.svc.cluster.local FALCOCTL_PATH=/tmp/certs falcoctl install tls`

Install latest falco version:
```
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
helm install --name falco \
--set ebpf.enabled=true \
--set falco.grpc.enabled=true \
--set falco.grpcOutput.enabled=true  \
--set-file certs.server.key=/tmp/server.key \
--set-file certs.server.crt=/tmp/server.crt \
--set-file certs.ca.crt=/tmp/ca.crt \
falcosecurity/falco

```
Install d56be55bb8c1bb1f216ef6f2f4f3cedc48347d24 checkout of falco-exporter
```
git checkout d56be55bb8c1bb1f216ef6f2f4f3cedc48347d24
helm install --name falco-exporter \
--set-file certs.ca.crt=/tmp/ca.crt,certs.client.key=/tmp/client.key,certs.client.crt=/tmp/client.crt \
./deploy/helm/falco-exporter
```

**Expected behaviour**
See events falco detects on any pod 

**Screenshots**
![image](https://user-images.githubusercontent.com/32679117/84493735-f6058580-acb0-11ea-91f9-6e1ed137f625.png)

**Environment**

- Falco version:
```
georgebrianb@cloudshell:~/falco-exporter (disertatie-utm-sysdig)$ kubectl exec falco-w4tvr -- falco --version
Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045
```
- System info:
```
georgebrianb@cloudshell:~/falco-exporter (disertatie-utm-sysdig)$ kubectl exec falco-w4tvr -- falco --support | jq .system_info
Fri Jun 12 10:34:50 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Jun 12 10:34:50 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Fri Jun 12 10:34:51 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
{
  "machine": "x86_64",
  "nodename": "gke-cluster-1-default-pool-085bc47d-zc9f",
  "release": "4.19.102+",
  "sysname": "Linux",
  "version": "#1 SMP Tue Feb 11 05:33:03 PST 2020"
```
- Cloud provider or hardware configuration: Google Cloud Platform - GKE
- OS:
COS - specified above
- Kernel:
Specified above
- Installation method:
Via helm on GKE

**Comment by leogr** [comment]
Hi @georgebrianb 

Thanks for reporting this!

Since the current release ( v0.1.0 ) does not fetch namespace/pod names metadata from the gRPC APIs yet, those namespace/pod names relate to the `falco-expoter` instance which caught the event and not the where the event was generated.

I agree with you that this is misleading, and I apologize for that.

However, we have good news :)
The correct namespace/pod names were added by this PR https://github.com/falcosecurity/falco-exporter/pull/32 and will be included in the next release.

We still have to fix them in the grafana dashboard accordingly. I will fix that.
