### ISSUE TITLE
Cannot view the falco logs in grafana

### ISSUE THREAD

**Issue by vignesh-codes** [falcosecurity/falco-exporter#43]
**How to view the falco logs in grafana as given in your readme.md figure?**
I installed the falco-exporter via helm. I can view the metric values without any error at http://127.0.0.1:9376/metrics. 

I want to view in grafana as given in the readme.md. I followed the steps to import the json but it shows me no data. 

How to view the falco logs in grafana as given in your readme.md picture?
I already installed Prometheus using helm and have enabled falco in my desktop cli too. They work fine. Only got stuck on viewing the falco logs in grafana.

**Comment by leogr** [comment]
I have no enough info to reproduce your problem. If you can provide all the steps you did with all details, I will be happy to help.

Anyway, a quick troubleshooting checklist:
- Has Prometheus detected the falco-exporter target?
- Has the Prometheus endpoint (e.g., `http://prom-prometheus-server.default.svc.cluster.local`) been added to the Grafana data sources?

**Comment by vignesh-codes** [comment]
I did this to install falco

```bash
helm install falco \
  --set falco.grpc.enabled=true \
  --set falco.grpcOutput.enabled=true \
  --set grafanaDashboard.enabled=true \
  --set serviceMonitor.enabled=true \
  falcosecurity/falco

helm install falco-exporter \
  --set falco.grpc.enabled=true \
  --set falco.grpcOutput.enabled=true \
  --set grafanaDashboard.enabled=true \
  --set serviceMonitor.enabled=true \
  falcosecurity/falco-exporter
```
It then tells me to export the POD_NAME and forward the port. I can view the metric value at http://127.0.0.1:9376/metrics.

i installed grafana using helm and it is in my default namespace of kubectl like this:
![image](https://user-images.githubusercontent.com/51945617/95210041-acfdb200-0808-11eb-80a7-6c8b11790b6d.png)


I started grafnana, logged in, and created a new dashboard. I imported the json as given here https://github.com/falcosecurity/falco-exporter/blob/master/grafana/dashboard.json . Also tried the id value to import. But i dont get the dashboard as given in your readme. Infact, grafana shows no data at all after importing those json. 

The grafana can show my falco pods running with some default cpu usage and network dashboards and all.

**Comment by leogr** [comment]
Firstly, the commands you used seem to be not correct to me, although that should not affect the installation. The correct ones should be:
```
helm install falco \
  --set falco.grpc.enabled=true \
  --set falco.grpcOutput.enabled=true \
  falcosecurity/falco

helm install falco-exporter \
  --set serviceMonitor.enabled=true \
  falcosecurity/falco-exporter
```

Then, more important: before importing the dashboard, you need to [add the datasource](https://grafana.com/docs/grafana/latest/features/datasources/add-a-data-source/) (ie. Prometheus) to Grafana as explained [in the Grafana documentation](https://grafana.com/docs/grafana/latest/features/datasources/add-a-data-source/).
The datasource type is Prometheus ofc, and the endpoint should be something like `http://<your-prometheus-service-name>.default.svc.cluster.local` (for the `default` namespace, change it accordingly if you deployed it in another namespace).

Have you done that yet?

**Comment by leogr** [comment]
Any news?

**Comment by vignesh-codes** [comment]
hi, will try this weekend and update. Thanks!

**Comment by vignesh-codes** [comment]
Hi @leogr 
So these are my services. Which one should I put? I am getting bad gateway error. Not sure which one to add the URL coloumn in data sources (Prometheus)
![image](https://user-images.githubusercontent.com/51945617/95597293-0fa2b800-0a6c-11eb-83fc-372afb84d7ea.png)

**Comment by leogr** [comment]
Hi @vignesh-codes 

since I don't know your installation details, I cannot be sure. I guess `prometheus-operated`, anyways. 

But, refer to the official Grafana and Prometheus (operator), please.

**Comment by vignesh-codes** [comment]
Hi!
I tried in my other pc and it works fine. Thanks

**Comment by nimeshitaliya** [comment]
Hi
As here we are deploying Prometheus operator so we need to add operator release name while deploying falco-exporter
values.yaml
```
serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
```
```
$ helm install falco-exporter -f values.yaml  falcosecurity/falco-exporter
```

Note: This change only apply for Prometheus operator - [Ref](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape)
