### ISSUE TITLE
Is this project overriden by https://github.com/falcosecurity/falcosidekick?

### ISSUE THREAD

**Issue by q2dg** [falcosecurity/falco-exporter#46]
Thanks!

**Comment by leogr** [comment]
Hey @q2dg 

No, this project is not overridden by falcosidekick. Although falcosidekick has recently introduced a similar functionality among many others, this project remains a single purpose and lightweight tool for exporting Falco output events metrics to Prometheus. Moreover, falco-exporter uses gRCP API and can provide more information (like the `hostname` value available via gRCP API only). And I think we can get metrics about drops here very soon (see #12).

So I truly believe the two projects can co-exist, even if that's a bit redundant.

Thank you for the question. It surely will help folks to understand better. :+1:

**Comment by q2dg** [comment]
Thanks a lot for your so clear explanation!!
I'll close this issue because it's already resolved.
Thanks!

**Comment by leogr** [comment]
You are welcome!
Happy to have been helpful :smiley_cat:
