### ISSUE TITLE
Add mTLS (optionally) for exporter metrics endpoint

### ISSUE THREAD

**Issue by jasiam** [falcosecurity/falco-exporter#47]
**Motivation**

Since falco-exporter could show falco alerts on its metrics endpoint, and these alerts could contain sensitive information like passwords, usernames, internal endpoints, etc... There should be a way to enable mTLS in exporter server so only allowed clients (e.g: Prometheus) is able to retrieve alerts

**Feature**

Add arguments to specify a CA file, a server certificate and implement the mTLS logic in root.go file (I'll try to fork the project and make a PR but I'm not a Go guy)

**Alternatives**

Going without TLS

**Additional context**

N/A

**Comment by leogr** [comment]
Nice feature! 

Your contribution is welcome :smiley:  

Let me know if you need any support, I'm happy to help. 
Also, feel free to contact (you can find me in the #falco channel on the [Kubernetes Slack](https://slack.k8s.io/))
