### ISSUE TITLE
Enhance Gauge Metrics

### ISSUE THREAD

**Issue by Dentrax** [falcosecurity/falco-exporter#70]
**Motivation**

Currently, there is only [1 gauge vector metric](https://github.com/falcosecurity/falco-exporter/blob/c0a091e174a9a9af651f34fd4a4996420834cbb5/pkg/exporter/exporter.go#L14-L29) in falco-exporter, that is `falco_events`. But it emits `string` values, I mean, we use Prometheus as a _log aggregator_ here. Pushing a bunch of string values to a time series DB is not that good practice. Users may already use a log aggregator to catch Falco logs and push them to remote. So, we decided not to continue with falco-exporter since there are no useful metrics additional to what we're collecting or want to collect.

**Feature**

* Do not emit `falco_events`
* Gauge: _dropped event count_
* Gauge: _webserver requests & latency & retry & dropped_
* Gauge: _audits scanned_
* Gauge: _rules active_
* Gauge: _events_
* ... etc.

**Alternatives**

`-`

**Additional context**

See https://github.com/falcosecurity/falco/issues/1772 brainstorming issue to support these metrics built-in in Falco.

**Comment by leogr** [comment]
cc @jasondellaluce

**Comment by Dentrax** [comment]
> Hey @Dentrax 
> 
> 
> 
> Any chance you would like to work on this? :angel: 

Hey!

I'm always ready to help! But my 2 cents here is to discuss and finalize the https://github.com/falcosecurity/falco/issues/1772 first before taking further actions on this. I'd like to give a hand but meantime you can assign good-fist-issue label in case if someone want to get into it. 😊
