### ISSUE TITLE
No falco_events shown on the /metrics endpoint

### ISSUE THREAD

**Issue by jsmith97** [falcosecurity/falco-exporter#81]
Hi, I am trying to run falco in a kind cluster with falco, falco-exporter, prometheus and grafana.
The falco container works fine and shows falco event in its log but the falco-exporter does not show any metrics for falco_events
```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 4.8412e-05
go_gc_duration_seconds{quantile="0.25"} 7.0107e-05
go_gc_duration_seconds{quantile="0.5"} 7.2428e-05
go_gc_duration_seconds{quantile="0.75"} 0.000410173
go_gc_duration_seconds{quantile="1"} 0.000410173
go_gc_duration_seconds_sum 0.00060112
go_gc_duration_seconds_count 4
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 16
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.17.13"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 4.391568e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.0727472e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4604
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 15719
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 4.695512e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 4.391568e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 2.62144e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 5.046272e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 19572
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 1.941504e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.667712e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6681264031141925e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 35291
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 4800
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 60656
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 81920
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.917344e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 922428
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 720896
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 720896
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.4109456e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 9
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.26
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 12
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.6171008e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.66812608442e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.30537984e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 12
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```
the logs from both containers look good to me and prometheus is happily scaping the falco-exporter metrics but as there are no falco_events it an only see the metrics listed above.
falco
│ Thu Nov 10 23:53:46 2022: Falco version: 0.33.0 (x86_64)                                                                                                                                                                   │
│ Thu Nov 10 23:53:46 2022: Falco initialized with configuration file: /etc/falco/falco.yaml                                                                                                                                 │
│ Thu Nov 10 23:53:46 2022: Loading rules from file /etc/falco/falco_rules.yaml                                                                                                                                              │
│ Thu Nov 10 23:53:46 2022: Loading rules from file /etc/falco/falco_rules.local.yaml                                                                                                                                        │
│ Thu Nov 10 23:53:46 2022: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)                                                                                                                                    │
│ Thu Nov 10 23:53:46 2022: gRPC server threadiness equals to 4                                                                                                                                                              │
│ Thu Nov 10 23:53:46 2022: Starting health webserver with threadiness 4, listening on port 8765                                                                                                                             │
│ Thu Nov 10 23:53:46 2022: Starting gRPC server at unix:///run/falco/falco.sock                                                                                                                                             │
│ Thu Nov 10 23:53:46 2022: Enabled event sources: syscall                                                                                                                                                                   │
│ Thu Nov 10 23:53:46 2022: Opening capture with Kernel module                                                                                                                                                               │
│ 23:54:15.799925365: Warning Mount was executed inside a privileged container (user=<NA> user_loginuid=-1 command=mount -t tmpfs -o size=16623497216 tmpfs /var/lib/kubelet/pods/9e5b0581-b368-4bff-aafb-b49d689c95d6/volum │
│ es/kubernetes.io~projected/kube-api-access-nqbv5 pid=1968957 k8s.ns=<NA> k8s.pod=<NA> container=9b8641703f36 image=kindest/node:v1.25.3)  
Falco-exporter
│ 2022/11/11 00:21:24 connecting to gRPC server at unix:///run/falco/falco.sock (timeout 2m0s)                                                                                                                               │
│ 2022/11/11 00:21:24 connected to gRPC server, subscribing events stream                                                                                                                                                    │
│ 2022/11/11 00:21:24 ready                                                                                                                                                                                                  │
│ 2022/11/11 00:21:24 listening on http://0.0.0.0:9376/metrics
```
does anyone know why the falco_events are not showing at http://0.0.0.0:9376/metrics? (edited)

**Comment by Happy-Dude** [comment]
Wanted to comment and mention that I was also experiencing this bug. What can we do on our side to debug this further?

**Comment by Happy-Dude** [comment]
Thanks for bringing up this issue in the Falco community call. 
Here are some extra debugging details from my end:

```
schan@debian:~$ falco --version
Falco version: 0.33.0-5-142ac8143e6
Libs version:  0.9.0
Plugin API:    2.0.0
Driver:
  API version:    2.0.0
  Schema version: 2.0.0
  Default driver: 3.0.1+driver
```

Relevant section of `falco.yaml`:
```
# gRPC server using an unix socket
grpc:
  enabled: true
  bind_address: "unix:///run/falco/falco.sock"
  # when threadiness is 0, Falco automatically guesses it depending on the number of online cores
  threadiness: 0

# gRPC output service.
# By default it is off.
# By enabling this all the output events will be kept in memory until you read them with a gRPC client.
# Make sure to have a consumer for them or leave this disabled.
grpc_output:
  enabled: true
```

falco-exporter run from terminal that continues to time out:
```
schan@debian:~$ falco-exporter --client-socket "unix:///run/falco/falco.sock"
2022/12/14 10:50:50 connecting to gRPC server at unix:///run/falco/falco.sock (timeout 2m0s)
2022/12/14 10:50:50 listening on http://:9376/metrics
2022/12/14 10:52:50 gRPC: error dialing server: context deadline exceeded
```

Output visiting the port from bridged networking (VM) -- no falco_events:
```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 13
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.4"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.362496e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.362496e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4620
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 307
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.616688e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.362496e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 4.54656e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.252224e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 2421
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 4.54656e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.798784e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 0
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 2728
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 7200
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 57600
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 65088
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 851748
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 589824
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 589824
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.2942352e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 10
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.05
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 10
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.1087872e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.67103640368e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.343533056e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

**Comment by Happy-Dude** [comment]
@leogr pointed out that `falco-exporter` needed to run with sudo/root privileges, and that corrected my issues:

* gRPC connection is established / no longer times out
* falco_events is generated

```
schan@debian:~$ sudo falco-exporter
2022/12/14 11:13:41 connecting to gRPC server at unix:///run/falco/falco.sock (timeout 2m0s)
2022/12/14 11:13:41 listening on http://:9376/metrics
2022/12/14 11:13:41 connected to gRPC server, subscribing events stream
2022/12/14 11:13:41 ready
```

Sample falco log events:
```
Dec 14 11:15:04 debian falco[735]: 11:15:04.924500039: Warning Shell history had been deleted or renamed (user=schan user_loginuid=1000 type=renameat command=nvim /home/schan/.bash_history pid=1825 fd.name=<NA> name=<NA> path=<NA> oldpath=/home/schan/.bash_history host (id=host))
Dec 14 11:15:04 debian falco[735]: 11:15:04.924533831: Warning a shell configuration file has been modified (user=schan user_loginuid=1000 command=nvim /home/schan/.bash_history pid=1825 pcmdline=bash file=/home/schan/.bash_history container_id=host image=<NA>)
```

Relevant section from `/metrics` endpoint:
```
# HELP falco_events 
# TYPE falco_events counter
falco_events{hostname="debian",k8s_ns_name="",k8s_pod_name="",priority="4",rule="Delete or rename shell history",source="syscall",tags=",mitre_defense_evasion,process,"} 1
falco_events{hostname="debian",k8s_ns_name="",k8s_pod_name="",priority="4",rule="Modify Shell Configuration File",source="syscall",tags=",file,mitre_persistence,"} 1
```

Thanks leogr; in conclusion, my issues were probably separate from issues relating to running falco, falco-exporter in a kind cluster. Apologies for the misdirection!

**Comment by jasondellaluce** [comment]
Thanks a lot @Happy-Dude! @jsmith97 can you check that you're running with sudo/root privileges and see if that fixes your issues?

**Comment by bryanasdev000** [comment]
For @jsmith97 could be related to the grpcOutput vs grpc_output confusion in chart docs.

Introduced here https://github.com/falcosecurity/charts/commit/73f42caf5b7e338fb23a0d05b688fc01287c3c71.

I have tested in the same setup (values.yaml) in the past and was wondering why was not working.

Turns out I was using grpcOutput not grpc_output, opened https://github.com/falcosecurity/charts/pull/436 to fix what I thought was the problem, but will do it inverse later.

**Comment by bryanasdev000** [comment]
Working like a charm now:

![Screenshot from 2022-12-27 14-25-36](https://user-images.githubusercontent.com/53131727/209700920-d04a338c-5065-4512-a6bf-d592e62821db.png)

**Comment by NissesSenap** [comment]
Thanks for this finding @bryanasdev000 !
So I read through this. The reason why it stopped working for me was due to the change in the helm chart.
Going from `grpcOutput` to `grpc_output` in the helm chart and apparently I missed it.
So I think you are wrong with your documentation change https://github.com/falcosecurity/charts/pull/436, my guess that most people is like me and we have missed the change how the falco configMap gets generated.

I have tried to follow the docs and not my own config but I guess I just did a bad job at testing because if I would have used the event-generator I would probably have gotten some events that would make it visible. Or I just changed some of these setting to match my own for some dumb reason.

Notice the usage of `grpc_output`

```shell
helm install falco \
  --set falco.grpc.enabled=true \
  --set falco.grpc_output.enabled=true \
  --set driver.kind=ebpf \
  falcosecurity/falco
```

Install falco-exporter

```shell
helm upgrade -i falco-exporter falcosecurity/falco-exporter
``` 

Install the event-generator

``` shell
helm install event-generator falcosecurity/event-generator \
  --namespace event-generator \
  --create-namespace \
  --set config.loop=false \
  --set config.actions=""
```

With this config I can now see output on AKS 1.24.

**Comment by bryanasdev000** [comment]
> Thanks for this finding @bryanasdev000 ! So I read through this. The reason why it stopped working for me was due to the change in the helm chart. Going from `grpcOutput` to `grpc_output` in the helm chart and apparently I missed it. So I think you are wrong with your documentation change [falcosecurity/charts#436](https://github.com/falcosecurity/charts/pull/436), my guess that most people is like me and we have missed the change how the falco configMap gets generated.
> 
> I have tried to follow the docs and not my own config but I guess I just did a bad job at testing because if I would have used the event-generator I would probably have gotten some events that would make it visible. Or I just changed some of these setting to match my own for some dumb reason.
> 
> Notice the usage of `grpc_output`
> 
> ```shell
> helm install falco \
>   --set falco.grpc.enabled=true \
>   --set falco.grpc_output.enabled=true \
>   --set driver.kind=ebpf \
>   falcosecurity/falco
> ```
> 
> Install falco-exporter
> 
> ```shell
> helm upgrade -i falco-exporter falcosecurity/falco-exporter
> ```
> 
> Install the event-generator
> 
> ```shell
> helm install event-generator falcosecurity/event-generator \
>   --namespace event-generator \
>   --create-namespace \
>   --set config.loop=false \
>   --set config.actions=""
> ```
> 
> With this config I can now see output on AKS 1.24.

it is, when I exit chaos mode at work I will fix it, in theory I should change a snippet of docs and a CI yaml:

https://github.com/falcosecurity/charts/search?q=grpcOutput

**Comment by bryanasdev000** [comment]
PR fixed.

**Comment by jasondellaluce** [comment]
@bryanasdev000 @NissesSenap thanks a lot for the in-depth walkthrough of the issue.

**Comment by leogr** [comment]
> I'm having this same issue, but don't have prometheus operator and i'm running falco & exporter outside k8s. I am missing /run/falco/falco.sock entirely, what populates this field?

`/run/falco/falco.sock` is created by Falco. The path depends on the Falco version and config. Please, provide all installation details. I'll try to help!

**Comment by leogr** [comment]
/remove-lifecycle rotten
/help

Hey folks, sorry I lost track of this. Anyway, I was not able to reproduce this problem. Is it still an issue? :thinking:

**Comment by leogr** [comment]
I wasn't able to reproduce this issue :(
