### ISSUE TITLE
(build) provide pre-built arm64 package

### ISSUE THREAD

**Issue by Happy-Dude** [falcosecurity/falco-exporter#84]
**Motivation**

There are only AMD64 packages available for `falco-exporter`.

If users want `falco-exporter` on ARM64 nodes, they have to compile/build from source manually.

**Feature**

* provide pre-built ARM64 packages

**Comment by FedeDP** [comment]
The change should be as simple as porting the [goreleaser](https://github.com/falcosecurity/falco-exporter/blob/master/.goreleaser.yml) config file to arm64 too, like event-generator does: https://github.com/falcosecurity/event-generator/blob/main/.goreleaser.yml!
