### ISSUE TITLE
falco-exporter secure unit file for running outside of kubernetes

### ISSUE THREAD

**Issue by cccsss01** [falcosecurity/falco-exporter#87]
**Motivation**

Is your feature request related to a problem?
Trying to create a secure unit file for falco exporter, hoping someone who understands it better may already have one and/or could add it to the documentation.

**Feature**

I would like a secure unit file for the falco exporter running outside of kubernetes.

**Alternatives**

Writing my own or running inside kubernetes

**Comment by leogr** [comment]
Could you elaborate more on this, please? It would be better if you could provide some examples.

Thanks

**Comment by therealbobo** [comment]
I think that @cccsss01 is referring to a systemd unit file applying the least privilege principle? Is that the case? 🤔

**Comment by johanneskastl** [comment]
For the record:
As far a systemd unit, I started packaging falco-exporter for openSUSE and used a slightly changed version of the falcosidekick systemd unit:

```
[Unit]
Description=Falco Exporter
After=network.target
StartLimitIntervalSec=0

[Service]
EnvironmentFile=/etc/sysconfig/falco-exporter

Type=simple
Restart=always
RestartSec=1
ExecStart=/usr/bin/falco-exporter $ARGS

[Install]
WantedBy=default.target
```

I need to test the full setup once I have working packages for falco, to check if the exporter can be run as an unprivileged user.
