### ISSUE TITLE
Do not finish execution when gRPC stream closed

### ISSUE THREAD

**Issue by sfairat15** [falcosecurity/falco-exporter#89]
**Motivation**

We have Falco installation at out k8s cluster. When we update Falco configs (customRules, for example), then all its DaemonSet pods recreating.

But at the same time all falco-exporters containers start restarting, because of `gRPC stream closed` [reason](https://github.com/falcosecurity/falco-exporter/blob/7a8f0cdef3ac14ca8af7148e7a1a98d7ef0d4027/cmd/falco-exporter/root.go#L101).

These massive container restarts raise alert "Too many container restarts" at our monitoring.

**Feature**

May be you can add some retry logic for grpc reconnect instead of application exit? Thanks.

**Additional context**

Some falco-exporter container setup:
```yaml
  containers:
  - args:
    - /usr/bin/falco-exporter
    - --client-socket=unix:///run/falco/falco.sock
    - --timeout=5m
    - --listen-address=0.0.0.0:9376
    image: docker.io/falcosecurity/falco-exporter:0.8.2
 ```

Falco-exporter log:
```console
> kubectl logs --previous falco-exporter-z64vp
2023/04/12 07:56:43 connecting to gRPC server at unix:///run/falco/falco.sock (timeout 5m0s)
2023/04/12 07:56:43 listening on http://0.0.0.0:9376/metrics
2023/04/12 07:56:46 connected to gRPC server, subscribing events stream
2023/04/12 07:56:46 ready
2023/04/27 11:23:48 gRPC stream closed
```

**Comment by leogr** [comment]
Hey @sfairat15 

Interesting. We can let `falco-exporter` try to reconnect by itself (ie. without exiting) using the already implemented connection backoff mechanism. Would it be enough?

PS
I'm not sure if this can create side-effects during normal shutdown operations (likely not, I need to check) :thinking:
